name: Testando build dotnet via github actions
on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 * * * *'
    
jobs:
  job_log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "logando o push"
