name: Testando workflow
on:
  push:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the job was triggered by a `${{github.event_name}}` event"
      - run: echo "drive is `${{github.event.inputs.homedrive}}`"
      - run: echo "environment is `${{github.event.inputs.environment}}`"
      - run: echo "log level is `${{github.event.inputs.logLevel}}`"
      - run: echo "run the matrix? `${{github.event.inputs.run_matrix}}`"
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo "status ${{job.status}}"
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo "services ${{job.services}}"
  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - run: echo "status ${{job.status}}"
